language: node_js
node_js:
- '5'
env:
- NODE_ENV=TEST CXX=g++-4.8
services:
- postgresql
addons:
  ssh_known_hosts: 95.85.25.10
  postgresql: '9.4'
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_script:
- psql -c 'create database expenses;' -U postgres
- sleep 15
install:
- travis_retry npm install -g node-gyp
- travis_retry npm install
- sleep 15
script:
- travis_retry npm run build
- travis_retry npm run lint
- travis_retry npm test
after_success:
- chmod 600 deploy-key
- mv deploy-key ~/.ssh/id_rsa
- rm -rf src/
- rm -rf node_modules/
- tar -czf jseminck-be-api-translation.tgz .
- scp -P 2222 jseminck-be-api-translation.tgz deploy@95.85.25.10:/home/apps/
- ssh -p 2222 deploy@95.85.25.10 'source ~/.bash_profile && cd /home/apps/ && ./deploy.sh jseminck-be-api-translation'
before_install:
- openssl aes-256-cbc -K $encrypted_fbdea3fe328e_key -iv $encrypted_fbdea3fe328e_iv
  -in deploy-key.enc -out deploy-key -d
